arg version=almalinux:9
from ${version}
env course="DevOps with AWS" \
    trainer="Sivakumar reddy" \
    duration="120hrs"
arg username=SumanthKumarTirumalasetti
run echo "Hello ${username}" > /tmp/devops.txt
cmd ["sleep" , "2000"]